### ISSUE TITLE
🐞 Bug Report: Issues with Injecting Secrets in Combined Job and CronJob Stack

### ISSUE THREAD

**Issue by PanupongDeve** [thaitype/kubricate#100]
## 🧵 Description

When both a Job and a CronJob are defined in the same Kubricate stack, the generated Kubernetes manifests 🔧 do not inject secrets 🔐 correctly.

### ⚠️ Observed Behavior
- When defining both a Job and a CronJob within the same Kubricate stack, the generated Kubernetes manifests fail to inject secrets correctly.
- This issue arises specifically when both Job and CronJob resources are present in the same stack.

## ⚠️ Issues files
PrivateCertStack.ts
```typescript
import { ResourceComposer, BaseStack, createStack } from '@kubricate/core';
import { PersistentVolumeClaim } from 'kubernetes-models/v1';
import { createMetadata } from '@kubricate/toolkit';
import { Job, type IJobSpec, CronJob } from 'kubernetes-models/batch/v1';
import { ClusterIssuer, Certificate } from '@kubernetes-models/cert-manager/cert-manager.io/v1';
import type { IPrivateCertStack } from './types.js';

export const PrivateCertStack = createStack('PrivateCertStack', (data: IPrivateCertStack) => {
  const generateMetadata = createMetadata(data.namespace ?? 'default');
  const jobTemplate: IJobSpec = {
    template: {
      spec: {
        containers: [
          {
            name: 'key2pfx',
            image: 'ghcr.io/thaitype/key2pfx:latest',
            env: [
              { name: 'KEY', value: '/certs/tls.key' },
              { name: 'CRT', value: '/certs/tls.crt' },
              { name: 'OUT', value: `/https/${data.pfxCertName}.pfx` },
            ],
            volumeMounts: [
              {
                mountPath: '/https/',
                name: 'key2pfx-v',
              },
              {
                mountPath: '/certs',
                name: 'private-cert',
              },
            ],
          },
        ],
        restartPolicy: 'Never',
        volumes: [
          {
            name: 'key2pfx-v',
            persistentVolumeClaim: {
              claimName: `${data.pfxCertName}-pvc`,
            },
          },
          {
            name: 'private-cert',
            secret: {
              secretName: data.secretCertName,
            },
          },
        ],
      },
    },
    backoffLimit: data.backoffLimit,
  };

  return new ResourceComposer()
    .addClass({
      id: 'cluster-issuer',
      type: ClusterIssuer,
      config: {
        metadata: generateMetadata(data.name, 'clusterIssuer'),
        spec: {
          selfSigned: {},
        },
      },
    })
    .addClass({
      id: 'certificate',
      type: Certificate,
      config: {
        metadata: generateMetadata(data.name, 'certificate'),
        spec: {
          secretName: data.secretCertName,
          issuerRef: {
            name: `${data.name}-cluster-issuer`,
            kind: 'ClusterIssuer',
          },
          commonName: data.commonName,
          dnsNames: data.dnsNames,
          duration: data.duration,
        },
      },
    })
    .addClass({
      id: 'pvc',
      type: PersistentVolumeClaim,
      config: {
        metadata: generateMetadata(`${data.pfxCertName}`, 'persistentVolumeClaim'),
        spec: {
          accessModes: ['ReadWriteMany'],
          resources: {
            requests: {
              storage: '10Mi',
            },
          },
          storageClassName: 'azurefile',
        },
      },
    })
    .addClass({
      id: 'job',
      type: Job,
      config: {
        metadata: generateMetadata(`${data.pfxCertName}`, 'job'),
        spec: jobTemplate,
      },
    })
    .addClass({
      id: 'cronJob',
      type: CronJob,
      config: {
        metadata: generateMetadata(`${data.pfxCertName}`, 'cronJob'),
        spec: {
          schedule: data.key2pfxCronCode,
          jobTemplate: {
            spec: jobTemplate,
          },
        },
      },
    });
});

```

File private-cert-stack.ts
```typescript
import { PrivateCertStack } from '@t-t-software-solution/platform-spec';
import { config } from "../shared-config.js";
import { secretRegistry } from '../setup-secret.js';

export const privateCertStack = PrivateCertStack.from({
    name: 'internal-tls',
    namespace: config.namespace,
    dnsNames: ['*.cluster.local', '*.domain.com'],
    duration: '8760h',
    commonName: 'domain.com',
    secretCertName: config.certificate.internal.secretName,
    pfxCertName: config.certificate.internal.pfxCertName,
    backoffLimit: 4,
    key2pfxCronCode: '0 0 * * *'
})
.useSecrets(secretRegistry.get('privateCertSecret-registry'), c => {
    c.secrets('Shared_PFX_DefaultPassword').intoResource("job").forName('PASSWORD').inject();
    c.secrets('Shared_PFX_DefaultPassword').intoResource("cronJob").forName('PASSWORD').inject('env', {
        targetPath: 'spec.jobTemplate.spec.template.spec.containers[0].env'
    });
  })

```
stacks.yml
We have PASSWORD KEY 2 key shouldbe 1 key 

❌Incorrect Config  in Job component 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: aspnetapp-job
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  template:
    spec:
      containers:
        - name: key2pfx
          image: ghcr.io/thaitype/key2pfx:latest
          env:
            - name: KEY
              value: /certs/tls.key
            - name: CRT
              value: /certs/tls.crt
            - name: OUT
              value: /https/aspnetapp.pfx
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idp-secret-provider
                  key: Shared_PFX_DefaultPassword
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idp-secret-provider
                  key: Shared_PFX_DefaultPassword
          volumeMounts:
            - mountPath: /https/
              name: key2pfx-v
            - mountPath: /certs
              name: private-cert
      restartPolicy: Never
      volumes:
        - name: key2pfx-v
          persistentVolumeClaim:
            claimName: aspnetapp-pvc
        - name: private-cert
          secret:
            secretName: internal-cert
  backoffLimit: 4
```
❌ incorrect  config in CronJob component 
```yaml
piVersion: batch/v1
kind: CronJob
metadata:
  name: aspnetapp-cronjob
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: key2pfx
              image: ghcr.io/thaitype/key2pfx:latest
              env:
                - name: KEY
                  value: /certs/tls.key
                - name: CRT
                  value: /certs/tls.crt
                - name: OUT
                  value: /https/aspnetapp.pfx
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: idp-secret-provider
                      key: Shared_PFX_DefaultPassword
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: idp-secret-provider
                      key: Shared_PFX_DefaultPassword
              volumeMounts:
                - mountPath: /https/
                  name: key2pfx-v
                - mountPath: /certs
                  name: private-cert
          restartPolicy: Never
          volumes:
            - name: key2pfx-v
              persistentVolumeClaim:
                claimName: aspnetapp-pvc
            - name: private-cert
              secret:
                secretName: internal-cert
      backoffLimit: 4
```
❌ full generated incorrect config file
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-tls-cluster-issuer
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-tls-cert
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  secretName: internal-cert
  issuerRef:
    name: internal-tls-cluster-issuer
    kind: ClusterIssuer
  commonName: domain.com
  dnsNames:
    - "*.cluster.local"
    - "*.domain.com"
  duration: 8760h
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnetapp-pvc
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: azurefile
---
apiVersion: batch/v1
kind: Job
metadata:
  name: aspnetapp-job
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  template:
    spec:
      containers:
        - name: key2pfx
          image: ghcr.io/thaitype/key2pfx:latest
          env:
            - name: KEY
              value: /certs/tls.key
            - name: CRT
              value: /certs/tls.crt
            - name: OUT
              value: /https/aspnetapp.pfx
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idp-secret-provider
                  key: Shared_PFX_DefaultPassword
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idp-secret-provider
                  key: Shared_PFX_DefaultPassword
          volumeMounts:
            - mountPath: /https/
              name: key2pfx-v
            - mountPath: /certs
              name: private-cert
      restartPolicy: Never
      volumes:
        - name: key2pfx-v
          persistentVolumeClaim:
            claimName: aspnetapp-pvc
        - name: private-cert
          secret:
            secretName: internal-cert
  backoffLimit: 4
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aspnetapp-cronjob
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: key2pfx
              image: ghcr.io/thaitype/key2pfx:latest
              env:
                - name: KEY
                  value: /certs/tls.key
                - name: CRT
                  value: /certs/tls.crt
                - name: OUT
                  value: /https/aspnetapp.pfx
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: idp-secret-provider
                      key: Shared_PFX_DefaultPassword
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: idp-secret-provider
                      key: Shared_PFX_DefaultPassword
              volumeMounts:
                - mountPath: /https/
                  name: key2pfx-v
                - mountPath: /certs
                  name: private-cert
          restartPolicy: Never
          volumes:
            - name: key2pfx-v
              persistentVolumeClaim:
                claimName: aspnetapp-pvc
            - name: private-cert
              secret:
                secretName: internal-cert
      backoffLimit: 4
---

```

## ✅ Expected Behavior
- Secrets should be correctly injected into both Job and CronJob resources.
- The generated configurations should be valid and deployable without errors.
- Example expected generated file

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: aspnetapp-job
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  template:
    spec:
      containers:
        - name: key2pfx
          image: ghcr.io/thaitype/key2pfx:latest
          env:
            - name: KEY
              value: /certs/tls.key
            - name: CRT
              value: /certs/tls.crt
            - name: OUT
              value: /https/aspnetapp.pfx
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: idp-secret-provider
                  key: Shared_PFX_DefaultPassword
          volumeMounts:
            - mountPath: /https/
              name: key2pfx-v
            - mountPath: /certs
              name: private-cert
      restartPolicy: Never
      volumes:
        - name: key2pfx-v
          persistentVolumeClaim:
            claimName: aspnetapp-pvc
        - name: private-cert
          secret:
            secretName: internal-cert
  backoffLimit: 4
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aspnetapp-cronjob
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: key2pfx
              image: ghcr.io/thaitype/key2pfx:latest
              env:
                - name: KEY
                  value: /certs/tls.key
                - name: CRT
                  value: /certs/tls.crt
                - name: OUT
                  value: /https/aspnetapp.pfx
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: idp-secret-provider
                      key: Shared_PFX_DefaultPassword
              volumeMounts:
                - mountPath: /https/
                  name: key2pfx-v
                - mountPath: /certs
                  name: private-cert
          restartPolicy: Never
          volumes:
            - name: key2pfx-v
              persistentVolumeClaim:
                claimName: aspnetapp-pvc
            - name: private-cert
              secret:
                secretName: internal-cert
      backoffLimit: 4
```

🧪 Steps to Reproduce

🖥️ Environment
OS: 🐧(Linux)
Bun version: 🟢 1.2.1
Node version: 🟢 v22.13.1
Kubricate version: 📦 0.17.0

🛠️ Suggested Fix / Workaround

I Fixing in file PrivateCertStack.ts
 - Clone job template object
 - Use job template object for Job component and cloned job template object for Cronjob component
 - 
 ```ts
import { ResourceComposer, BaseStack, createStack } from '@kubricate/core';
import { PersistentVolumeClaim } from 'kubernetes-models/v1';
import { createMetadata } from '@kubricate/toolkit';
import { Job, type IJobSpec, CronJob } from 'kubernetes-models/batch/v1';
import { ClusterIssuer, Certificate } from '@kubernetes-models/cert-manager/cert-manager.io/v1';
import type { IPrivateCertStack } from './types.js';

export const PrivateCertStack = createStack('PrivateCertStack', (data: IPrivateCertStack) => {
  const generateMetadata = createMetadata(data.namespace ?? 'default');
  const jobTemplate: IJobSpec = {
    template: {
      spec: {
        containers: [
          {
            name: 'key2pfx',
            image: 'ghcr.io/thaitype/key2pfx:latest',
            env: [
              { name: 'KEY', value: '/certs/tls.key' },
              { name: 'CRT', value: '/certs/tls.crt' },
              { name: 'OUT', value: `/https/${data.pfxCertName}.pfx` },
            ],
            volumeMounts: [
              {
                mountPath: '/https/',
                name: 'key2pfx-v',
              },
              {
                mountPath: '/certs',
                name: 'private-cert',
              },
            ],
          },
        ],
        restartPolicy: 'Never',
        volumes: [
          {
            name: 'key2pfx-v',
            persistentVolumeClaim: {
              claimName: `${data.pfxCertName}-pvc`,
            },
          },
          {
            name: 'private-cert',
            secret: {
              secretName: data.secretCertName,
            },
          },
        ],
      },
    },
    backoffLimit: data.backoffLimit,
  };

  // Clone Object, avoid call by reference when data in object update
  const clonedJobTemplate: IJobSpec = JSON.parse(JSON.stringify(jobTemplate));

  return new ResourceComposer()
    .addClass({
      id: 'cluster-issuer',
      type: ClusterIssuer,
      config: {
        metadata: generateMetadata(data.name, 'clusterIssuer'),
        spec: {
          selfSigned: {},
        },
      },
    })
    .addClass({
      id: 'certificate',
      type: Certificate,
      config: {
        metadata: generateMetadata(data.name, 'certificate'),
        spec: {
          secretName: data.secretCertName,
          issuerRef: {
            name: `${data.name}-cluster-issuer`,
            kind: 'ClusterIssuer',
          },
          commonName: data.commonName,
          dnsNames: data.dnsNames,
          duration: data.duration,
        },
      },
    })
    .addClass({
      id: 'pvc',
      type: PersistentVolumeClaim,
      config: {
        metadata: generateMetadata(`${data.pfxCertName}`, 'persistentVolumeClaim'),
        spec: {
          accessModes: ['ReadWriteMany'],
          resources: {
            requests: {
              storage: '10Mi',
            },
          },
          storageClassName: 'azurefile',
        },
      },
    })
    .addClass({
      id: 'job',
      type: Job,
      config: {
        metadata: generateMetadata(`${data.pfxCertName}`, 'job'),
        spec: jobTemplate,
      },
    })
    .addClass({
      id: 'cronJob',
      type: CronJob,
      config: {
        metadata: generateMetadata(`${data.pfxCertName}`, 'cronJob'),
        spec: {
          schedule: data.key2pfxCronCode,
          jobTemplate: {
            spec: clonedJobTemplate,
          },
        },
      },
    });
});

```
