### ISSUE TITLE
Feature Support Resource Allocation for Low Resources

### ISSUE THREAD

**Issue by mildronize** [thaitype/kubricate#129]
Example
```yml
resources:
  requests:
        cpu: 10m
        memory: 125Mi
      limits:
        cpu: 500m
        memory: 1024Mi
```
