### ISSUE TITLE
Feature: Secret Injection Support for Helm Charts

### ISSUE THREAD

**Issue by mildronize** [thaitype/kubricate#55]
### Summary

This feature adds **first-class support for injecting secrets into Helm charts**, allowing developers to securely manage and configure Helm releases (e.g., Bitnami PostgreSQL) using the Kubricate `useSecrets()` API.

Supports both:

- 🔑 Kubernetes secrets (e.g. `env`, `existingSecret`)
- 🔐 Vault annotations (e.g. `vault.hashicorp.com/*`)

---

### ✨ Motivation

In real-world applications, Helm charts often require sensitive configurations such as:

- Database passwords
- API keys
- Vault injection annotations

Manually editing `.Values` is error-prone and doesn't leverage type-safety. This feature allows seamless, flexible, **type-safe secret injection** into Helm values using familiar Kubricate patterns.

---

### 📦 1. Install Helm Package

```bash
kubricate install bitnami/postgresql --version 15.5.0 --provider helm
```

Creates:

- `kubricate.package.json` (metadata)
- `.gen/BitnamiPostgresqlHelmStack.ts` (stack interface from Helm schema)

---

### 🔐 2. Inject Kubernetes Secret (e.g. `env`)

```tsx
injector.secrets('db-password')
  .inject('helmValue', secret => ({
    primary: {
      extraEnvVars: [
        {
          name: 'POSTGRES_PASSWORD',
          valueFrom: {
            secretKeyRef: {
              name: secret.name,
              key: secret.meta.key,
            },
          },
        },
      ],
    },
  }));
```

**Resulting Helm values:**

```yaml
primary:
  extraEnvVars:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: db-password

```

---

### 🔐 3. Inject Vault Annotations

```tsx
injector.secrets('db-password')
  .forName('POSTGRES_PASSWORD')
  .inject('helmValue', secret => ({
    annotations: {
      'vault.hashicorp.com/agent-inject': 'true',
      [`vault.hashicorp.com/agent-inject-secret-${secret.meta.targetName}`]: `secret/data/db#password`,
    },
  }));
```

**Resulting annotations:**

```yaml
annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-secret-POSTGRES_PASSWORD: "secret/data/db#password"
```

---

### 🧠 Design Goals

- ✅ Support arbitrary `.Values` injection using `.inject('helmValue', fn)`
- ✅ Type-safe `secret.name`, `secret.meta.targetName`, `secret.meta.key`
- ✅ Optional `.forName()` to override environment key
- ✅ Compatible with any Helm chart (via `kubricate get`)
- ✅ Works without modifying secrets core logic

---

### 🛠 Internal Implementation Plan

- Extend `SecretInjectionBuilder.inject(kind: 'helmValue', transformFn)` overload
- Register transformed result into a new `helmOverrides` tree
- Merge during Helm stack `build()` with `.values.yaml`
