### ISSUE TITLE
Bug: createStack() returns duplicate manifests instead of unique per .from(...)

### ISSUE THREAD

**Issue by PanupongDeve** [thaitype/kubricate#62]
When using `createStack()` to instantiate multiple stacks from the same definition, the generated manifests are not isolated. Instead, the last` .from()` call appears to override the previous one.

### 🧪 **Reproducible Example**

```typescript
import { createStack, ResourceComposer } from '@kubricate/core';
import { Namespace } from 'kubernetes-models/v1';

interface MyInput {
  name: string;
}

const MyStack = createStack('MyStack', (data: MyInput) => {
  return new ResourceComposer().addClass({
    id: 'namespace',
    type: Namespace,
    config: {
      metadata: { name: data.name },
    },
  });
});

export const frontend = MyStack.from({
  name: 'frontend-namespace',
});

export const backend = MyStack.from({
  name: 'backend-namespace',
});
```

### ❌ Actual Output
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: backend-namespace
  labels:
    thaitype.dev/managed-by: kubricate
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-namespace
  labels:
    thaitype.dev/managed-by: kubricate

```

### ✅ Expected Output
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-namespace
  labels:
    thaitype.dev/managed-by: kubricate
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-namespace
  labels:
    thaitype.dev/managed-by: kubricate
```

### 📌 Possible Cause
`createStack() `appears to return a shared instance of the same `BaseStack `object. So each call to` .from()` mutates the same underlying composer instead of creating a new one.

### ✅ Suggested Fix
Update the `createStack()` implementation to:

- Return a **factory function** that always creates a new instance
- Ensure each `.from(...)` call returns a unique `BaseStack` with isolated internal state

### 📎 Related
- Stack instance should be stateless across `.from()` calls
- Could consider moving to a `.create()` style pattern instead of `.from()` on a shared object
