### ISSUE TITLE
OpaqueSecretProvider not support CronJob secret injection target Path

### ISSUE THREAD

**Issue by PanupongDeve** [thaitype/kubricate#91]
When executing the command `bun run kbr generate --root ./examples`, the generated Kubernetes manifest for the `CronJob `resource does not correctly inject environment variables.

💡 **Expected Behavior:** The `template block`section within the `Kind: Cronjob`specification should correctly reference environment variables✅

😕**Actual Behavior:** The generated YAML includes an `env `section with `template block`fields that do not correctly reference the intended sources.❌

🔁**Steps to Reproduce:**

1. Run the command:

```bash
bun run kbr generate --root ./examples
```

2. Inspect the generated CronJob YAML manifest.

**🧾Sample Output:**
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aspnetapp-cronjob
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: key2pfx
              image: ghcr.io/thaitype/key2pfx:latest
              env:
                - name: KEY
                  value: /certs/tls.key
                - name: CRT
                  value: /certs/tls.crt
                - name: OUT
                  value: /https/aspnetapp.pfx
              volumeMounts:
                - mountPath: /https/
                  name: key2pfx-v
                - mountPath: /certs
                  name: private-cert
          restartPolicy: Never
          volumes:
            - name: key2pfx-v
              persistentVolumeClaim:
                claimName: aspnetapp-pvc
            - name: private-cert
              secret:
                secretName: internal-cert
      backoffLimit: 4
  template:
    spec:
      containers:
        - env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-application
                  key: Shared_PFX_DefaultPassword
```

**🧾Expected result**

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aspnetapp-cronjob
  namespace: demo-corp-ns
  labels:
    thaitype.dev/managed-by: kubricate
spec:
  schedule: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: key2pfx
              image: ghcr.io/thaitype/key2pfx:latest
              env:
                - name: KEY
                  value: /certs/tls.key
                - name: CRT
                  value: /certs/tls.crt
                - name: OUT
                  value: /https/aspnetapp.pfx
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secret-application
                      key: Shared_PFX_DefaultPassword
              volumeMounts:
                - mountPath: /https/
                  name: key2pfx-v
                - mountPath: /certs
                  name: private-cert
          restartPolicy: Never
          volumes:
            - name: key2pfx-v
              persistentVolumeClaim:
                claimName: aspnetapp-pvc
            - name: private-cert
              secret:
                secretName: internal-cert
      backoffLimit: 4
            
```
